[platformio]
default_envs = tag

[env]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  symlink://../lib/Dw3000

[env:tag]
build_src_filter = +<tag.cpp> -<anchor.cpp>

[env:anchor]
build_src_filter = +<anchor.cpp> -<tag.cpp>
