[platformio]
default_envs = tag

[env]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  symlink://../lib/Dw3000

[env:tag]
build_src_filter = +<tag.cpp> -<anchor.cpp>
build_flags = -DTAG_ID=0

[env:anchor-01]
build_src_filter = +<anchor.cpp> -<tag.cpp>
build_flags = -DANCHOR_ID=0xA0

[env:anchor-02]
build_src_filter = +<anchor.cpp> -<tag.cpp>
build_flags = -DANCHOR_ID=0xA1

[env:anchor-03]
build_src_filter = +<anchor.cpp> -<tag.cpp>
build_flags = -DANCHOR_ID=0xA2

[env:anchor-04]
build_src_filter = +<anchor.cpp> -<tag.cpp>
build_flags = -DANCHOR_ID=0xA3
